### ISSUE TITLE
in multi-word strings, separators aren't removed from words[1:]

### ISSUE THREAD

**Issue by sperand-io** [ianstormtaylor/to-no-case#2]
failure case: https://github.com/segmentio/integration-mailchimp/pull/15

**Comment by ianstormtaylor** [comment]
Ah I think this might be just the goal for `to-no-case` not being clear. I think it's goal is to remove all "casing", but keep any word separations that need to be conveyed in the case to convert it to. Such that from `to-no-case` you can get to `snake`, `title`, `sentence`, etc. still without loss.

But there could be an argument for a `to-snug-case` or similar that makes things `snugcase` or an upper version of it.

**Comment by sperand-io** [comment]
makes sense!
