### ISSUE TITLE
Support Unicode casing

### ISSUE THREAD

**Issue by magnushiie** [ianstormtaylor/to-no-case#3]
This (and therefore the whole case helpers module grroup) currently only supports ASCII, with non-ASCII characters silently stripped.

**Comment by ianstormtaylor** [comment]
Thanks for reporting. I'd be down for a PR if you're open to submitting one!

**Comment by magnushiie** [comment]
You are welcome to close this, because since I reported this issue, I moved on to using https://github.com/blakeembrey/title-case that supports Unicode
